apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-api-deployment
  labels:
    app: aggregator-api
spec:
  selector:
    matchLabels:
      app: aggregator-api
  replicas: 1
  template:
    metadata:
      labels:
        app: aggregator-api
    spec:
      containers:
      - name: aggregator-api
        image: varundora/aggregatorservice:latest
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: aggregatorservice
spec:
  selector:
    app: aggregator-api
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 31000
  type: NodePort